export const ADD_ANIMAL = 'ADD_ANIMAL';
export const UPDATE_ANIMAL = 'UPDATE_ANIMAL';
export const DELETE_ANIMAL = 'DELETE_ANIMAL';
export const INIT_ANIMAL = 'INIT_ANIMAL';
export const ANIMAL_TO_PUBLIC = 'ANIMAL_TO_PUBLIC';
export const INIT_CURRENT_ANIMAL = 'INIT_CURRENT_ANIMAL';

export const ANIMAL_RESPONSE_SUCCESS = 'ANIMAL_RESPONSE_SUCCESS';
export const ANIMAL_RESPONSE_ERROR = 'ANIMAL_RESPONSE_ERROR';
export const ANIMAL_RESPONSE_PENDING = 'ANIMAL_RESPONSE_PENDING';
