export const ADD_ITEM_BASKET = 'ADD_ITEM_BASKET';
export const UPDATE_ITEM_BASKET = 'UPDATE_ITEM_BASKET';
export const DELETE_ITEM_BASKET = 'DELETE_ITEM_BASKET';
export const INIT_ITEMS_BASKET = 'INIT_ITEMS_BASKET';
export const CLEAR_BASKET = 'CLEAR_BASKET';
export const APPLY_PROMO = 'APPLY_PROMO';
