export const ADD_ITEM = 'ADD_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const INIT_ITEMS = 'INIT_ITEMS';
export const INIT_CURRENT_ITEM = 'INIT_CURRENT_ITEM';
export const INIT_ITEM_LIST = 'INIT_ITEM_LIST';

export const INIT_CATEGORIES = 'INIT_CATEGORIES';

export const ITEM_RESPONSE_SUCCESS = 'ITEM_RESPONSE_SUCCESS';
export const ITEM_RESPONSE_PENDING = 'ITEM_RESPONSE_PENDING';
export const ITEM_RESPONSE_ERROR = 'ITEM_RESPONSE_ERROR';

export const INIT_RELATIVE_ITEMS = 'INIT_RELATIVE_ITEMS';
