export const GET_REVIEWS = 'GET_REVIEWS';
export const CREATE_REVIEW = 'CREATE_REVIEW';
export const SET_REVIEWS_LIST = 'SET_REVIEWS_LIST';
export const REVIEW_TO_PUBLIC = 'REVIEW_TO_PUBLIC';
export const DELETE_REVIEW = 'DELETE_REVIEW';

export const REVIEW_RESPONSE_SUCCESS = 'REVIEW_RESPONSE_SUCCESS';
export const REVIEW_RESPONSE_ERROR = 'REVIEW_RESPONSE_ERROR';
export const REVIEW_RESPONSE_PENDING = 'REVIEW_RESPONSE_PENDING';
