module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert('Items', [
      // корма для кошек
      {
        title:
          'Корм Pronature Holistic для котят: Курица со сладким картофелем',
        description:
          'Pronature Holistic индейка с клюквой для взрослых кошек, живущих в дома. Созданный с использованием самых последних исследований в диетологии, корм помогает кошкам, живущим в помещении, сохранить здоровье и хорошую форму благодаря контролю уровня калорийности и технологии выведения комков шерсти из ЖКТ',
        price: 3400,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/a6/ce/e2/499315_400x400.jpg',
        rating: 0,
        categoryType_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Корм Pronature Holistic Лайт для взрослых кошек: Океаническая белая рыба с рисом, облегченный',
        description:
          'Pronature Holistic индейка с клюквой для взрослых кошек, живущих в дома. Созданный с использованием самых последних исследований в диетологии, корм помогает кошкам, живущим в помещении, сохранить здоровье и хорошую форму благодаря контролю уровня калорийности и технологии выведения комков шерсти из ЖКТ',
        price: 3140,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/12/a5/30/499311_400x400.jpg',
        rating: 0,
        categoryType_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Корм Pronature Holistic для взрослых кошек: Утка с апельсином',
        description:
          'Pronature Holistic индейка с клюквой для взрослых кошек, живущих в дома. Созданный с использованием самых последних исследований в диетологии, корм помогает кошкам, живущим в помещении, сохранить здоровье и хорошую форму благодаря контролю уровня калорийности и технологии выведения комков шерсти из ЖКТ',
        price: 3913,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/b2/49/6e/499309_400x400.jpg',
        rating: 0,
        categoryType_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Корм Pronature Holistic для взрослых кошек: Лосось и рис, для здоровья кожи и шерсти',
        description:
          'Pronature Holistic индейка с клюквой для взрослых кошек, живущих в дома. Созданный с использованием самых последних исследований в диетологии, корм помогает кошкам, живущим в помещении, сохранить здоровье и хорошую форму благодаря контролю уровня калорийности и технологии выведения комков шерсти из ЖКТ',
        price: 3600,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/c9/b6/83/499314_400x400.jpg',
        rating: 0,
        categoryType_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Корм Pronature Holistic для взрослых кошек: Индейка с клюквой',
        description:
          'Pronature Holistic индейка с клюквой для взрослых кошек, живущих в дома. Созданный с использованием самых последних исследований в диетологии, корм помогает кошкам, живущим в помещении, сохранить здоровье и хорошую форму благодаря контролю уровня калорийности и технологии выведения комков шерсти из ЖКТ',
        price: 3500,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/7e/75/d2/499313_400x400.jpg',
        rating: 0,
        categoryType_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Корм NOW FRESH беззерновой для кошек "Контроль веса" с индейкой, уткой и овощами',
        description:
          'NOW FRESH – единственный корм класса холистик, который производится из 100% свежего мяса и не содержит зерновых. В кормах соблюдается оптимальное сочетание белков и жиров для здоровья и долголетия Вашего питомца. При производстве кормов используется только свежее мясо индейки, утки, лосося, кокосовое и рапсовое масло.',
        price: 4915,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/6e/4b/a3/540085_400x400.jpg',
        rating: 0,
        categoryType_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Корм NOW FRESH беззерновой для котят, с индейкой, уткой и овощами',
        description:
          'В кормах соблюдается оптимальное сочетание белков и жиров для здоровья и долголетия вашего питомца. При производстве кормов используется только свежее мясо индейки, утки, лосося, кокосовое и рапсовое масло.',
        price: 5200,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/ea/74/7a/534705_400x400.jpg',
        rating: 0,
        categoryType_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Корм NOW FRESH беззерновой для взрослых кошек, с форелью и лососем для чувствительного пищеварения',
        description:
          'NOW FRESH – единственный корм класса холистик, который производится из 100% свежего мяса и не содержит зерновых. В кормах соблюдается оптимальное сочетание белков и жиров для здоровья и долголетия вашего питомца. При производстве кормов используется только свежее мясо индейки, утки, лосося, кокосовое и рапсовое масло.',
        price: 5340,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/05/59/6b/534713_400x400.jpg',
        rating: 0,
        categoryType_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Корм NOW FRESH беззерновой для взрослых кошек с индейкой, уткой и овощами',
        description:
          'Полностью сбалансированный корм класса холистик  для взрослых кошек из филе индейки и утки, выращенных на канадских фермах, из бескостного филе лосося, выловленного в озерах Британской Колумбии.',
        price: 5400,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/57/53/88/540051_400x400.jpg',
        rating: 0,
        categoryType_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Корм GO! беззерновой для котят и кошек с чувствительным пищеварением, со свежей уткой',
        description:
          'Корма GO! Sensitivities разработаны специально для кошек с особыми потребностями в питании, поэтому идеально подходят для животных с чувствительным пищеварением.Все рецепты линейки GO! Sensitivities имеют одинаковые базовые компоненты, благодаря чему вы можете легко переводить питомца с одного корма на другой в пределах линейки без выделения времени на привыкание.',
        price: 4500,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/77/83/93/511377_400x400.jpg',
        rating: 0,
        categoryType_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Корм GO! беззерновой для котят и кошек с чувствительным пищеварением с форелью и лососем',
        description:
          'Корма GO! Sensitivities разработаны специально для кошек с особыми потребностями в питании, поэтому идеально подходят для животных с чувствительным пищеварением.Все рецепты линейки GO! Sensitivities имеют одинаковые базовые компоненты, благодаря чему вы можете легко переводить питомца с одного корма на другой в пределах линейки без выделения времени на привыкание.',
        price: 4500,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/77/83/93/511377_400x400.jpg',
        rating: 0,
        categoryType_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Корм GO! для котят и кошек, со свежей курицей, фруктами и овощами',
        description:
          'Корма GO! Sensitivities разработаны специально для кошек с особыми потребностями в питании, поэтому идеально подходят для животных с чувствительным пищеварением.Все рецепты линейки GO! Sensitivities имеют одинаковые базовые компоненты, благодаря чему вы можете легко переводить питомца с одного корма на другой в пределах линейки без выделения времени на привыкание.',
        price: 4500,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/c4/40/19/511381_400x400.jpg',
        rating: 0,
        categoryType_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Корм GO! беззерновой для котят и кошек с чувствительным пищеварением с форелью и лососем',
        description:
          'Некоторые кошки определенно мясоеды, что говорит об их хищной природе. Этот беззерновой рецепт богат белками, обеспечивает полноценное и сбалансированное питание, чтобы помочь вашей кошке оставаться здоровой и сохранять отличную физическую форму.',
        price: 3500,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/70/87/14/511379_400x400.jpg',
        rating: 0,
        categoryType_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Papillon игрушка для кошек Светоотражающая мышка с погремушкой',
        description:
          'Всевозможные удочки-дразнилки, игрушки в виде животных, игрушки с погремушками и бубенчиками. Игрушки мягкие и твердые, шуршащие и звенящие, маленькие и побольше.',
        price: 90,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/26/f0/87/308722_400x400.jpg',
        rating: 0,
        categoryType_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Papillon игрушка для кошек "Мячик" с бубенчиком, зеленый, нейлон, 5 см',
        description:
          'Всевозможные удочки-дразнилки, игрушки в виде животных, игрушки с погремушками и бубенчиками. Игрушки мягкие и твердые, шуршащие и звенящие, маленькие и побольше.',
        price: 100,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/d8/e3/6f/308723_400x400.jpg',
        rating: 0,
        categoryType_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Корм Royal Canin для бывающих на улице кошек',
        description:
          'Некоторые кошки определенно мясоеды, что говорит об их хищной природе. Этот беззерновой рецепт богат белками, обеспечивает полноценное и сбалансированное питание, чтобы помочь вашей кошке оставаться здоровой и сохранять отличную физическую форму.',
        price: 2200,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/f4/1d/a1/312566_400x400.jpg',
        rating: 0,
        categoryType_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Антицарапки голубь сизый с валерианой',
        description:
          'Игрушка набита синтепухом. В нее добавлена кошачья мята и валериана, что увеличит вероятность проявления интереса к ней вашей кошки, так как одни кошки больше реагируют на кошачью мяту, а другие - на валериану.',
        price: 170,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/27/bc/c1/549433_400x400.jpg',
        rating: 0,
        categoryType_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Корм Royal Canin для кастрированных кошек и котов: 1-7 лет',
        description:
          'Некоторые кошки определенно мясоеды, что говорит об их хищной природе. Этот беззерновой рецепт богат белками, обеспечивает полноценное и сбалансированное питание, чтобы помочь вашей кошке оставаться здоровой и сохранять отличную физическую форму.',
        price: 2200,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/4f/68/b7/312598_400x400.jpg',
        rating: 0,
        categoryType_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Petsiki Динамическая когтеточка "Яйцо"',
        description:
          'Динамическая когтеточка "Яйцо" позволяет точить когти и играть одновременно. Благодаря принципу неваляшки клубок всегда возвращается в исходное положение, а безопасный джутовый канат помогает бережно точить когти. Вытянутая форма когтеточки позволяет удобно точить когти на задних лапах.',
        price: 500,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/4d/f4/c4/514442_400x400.jpg',
        rating: 0,
        categoryType_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Корм Royal Canin для комфортного пищеварения кошек от 1 года',
        description:
          'Некоторые кошки определенно мясоеды, что говорит об их хищной природе. Этот беззерновой рецепт богат белками, обеспечивает полноценное и сбалансированное питание, чтобы помочь вашей кошке оставаться здоровой и сохранять отличную физическую форму.',
        price: 2200,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/3f/52/00/382816_400x400.jpg',
        rating: 0,
        categoryType_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Catit Senses 2.0 Трек игровой малый',
        description:
          'Игровой малый трек - интерактивная игрушка, позволяющая составить более 100 конфигураций.',
        price: 1400,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/15/77/37/549548_400x400.jpg',
        rating: 0,
        categoryType_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Go! Консервы беззерновые с тушеной курицей, индейкой и мясом утки',
        description:
          'Некоторые кошки определенно мясоеды, что говорит об их хищной природе. Этот беззерновой рецепт богат белками, обеспечивает полноценное и сбалансированное питание, чтобы помочь вашей кошке оставаться здоровой и сохранять отличную физическую форму.',
        price: 220,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/db/9a/d6/425696_400x400.jpg',
        rating: 0,
        categoryType_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Triol занимательная игрушка для кошек "Пират"',
        description:
          'Игрушка стимулирует охотничьи навыки кошек и призывает их к активному выслеживанию добычи. Просто поставьте этот маяк перед животным и наблюдайте за тем, как кошка будет стараться поймать маленькую "рыбку" на конце маятника, используя всевозможные способы.',
        price: 1000,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/39/8e/3a/528677_400x400.jpg',
        rating: 0,
        categoryType_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Triol Marvel игровой туннель для кошек "Marvel" Человек-паук',
        description:
          'Мягкий, просторный, шуршащий и очень теплый, такой туннель станет не только прекрасным аксессуаром для активной игры, но и отличным местом для отдыха после интенсивных "кардионагрузок".',
        price: 1000,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/2d/4a/44/507845_400x400.jpg',
        rating: 0,
        categoryType_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Trixie игрушка "Обезьяна" с кошачьей мятой',
        description: 'Игрушка "Обезьяна" для кошек, размер: 12 см',
        price: 300,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/68/02/74/558408_400x400.jpg',
        rating: 0,
        categoryType_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Papillon игрушка для кошек "НЛО", 20х25 см, бирюзовая, плюш',
        description:
          'Игрушки мягкие и твердые, шуршащие и звенящие, маленькие и побольше. Также в ассортименте производителя Papillon представлены канаты для перетягивания, латексные игрушки для прорезывания зубов, плюшевые косточки, мышки из натурального меха и многое другое.',
        price: 1100,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/95/1c/3a/308725_400x400.jpg',
        rating: 0,
        categoryType_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Go! Консервы беззерновые с индейкой, для собак',
        description:
          'Некоторые кошки определенно мясоеды, что говорит об их хищной природе. Этот беззерновой рецепт богат белками, обеспечивает полноценное и сбалансированное питание, чтобы помочь вашей кошке оставаться здоровой и сохранять отличную физическую форму.',
        price: 380,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/c4/19/7d/425689_400x400.jpg',
        rating: 0,
        categoryType_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Petstages игрушка для кошек "Трек 3 этажа"',
        description:
          'Игровой трек с мячиками идеально подходит для одной или нескольких кошек. Яркий мячик катается по кругу, что очень привлекает внимание кошки. Оторваться невозможно! Как ни стараешься, всё равно не поймаешь, но и не потеряешь.',
        price: 1350,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/23/d6/3f/499342_400x400.jpg',
        rating: 0,
        categoryType_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Корм GO! для щенков и собак, со свежим лососем и овсянкой',
        description:
          'Некоторые кошки определенно мясоеды, что говорит об их хищной природе. Этот беззерновой рецепт богат белками, обеспечивает полноценное и сбалансированное питание, чтобы помочь вашей кошке оставаться здоровой и сохранять отличную физическую форму.',
        price: 4600,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/5e/cc/36/511383_400x400.jpg',
        rating: 0,
        categoryType_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Ferribiella аксессуары игрушка "Джунгли зовут"',
        description:
          'Не можете отучить щенка грызть обувь? Легальная альтернатива домашнему хулиганству - безопасна и полезна во время активного роста прорезывания зубов.',
        price: 900,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/fc/e0/06/416731_400x400.jpg',
        rating: 0,
        categoryType_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Корм NOW FRESH беззерновой "Контроль веса" для собак, с индейкой, уткой и овощами',
        description:
          'Некоторые кошки определенно мясоеды, что говорит об их хищной природе. Этот беззерновой рецепт богат белками, обеспечивает полноценное и сбалансированное питание, чтобы помочь вашей кошке оставаться здоровой и сохранять отличную физическую форму.',
        price: 2200,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/b4/48/2b/511386_400x400.jpg',
        rating: 0,
        categoryType_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Ferribiella аксессуары игрушка "Развяжи шнурок" латексная для собак',
        description:
          'Не можете отучить щенка грызть обувь? Легальная альтернатива домашнему хулиганству - безопасна и полезна во время активного роста прорезывания зубов.',
        price: 900,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/bb/5a/b5/417559_400x400.jpg',
        rating: 0,
        categoryType_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Papillon игрушка для собак "Зов Джунглей", 9 см, латекс',
        description:
          'Игрушки мягкие и твердые, шуршащие и звенящие, маленькие и побольше. Также в ассортименте производителя Papillon представлены канаты для перетягивания, латексные игрушки для прорезывания зубов, плюшевые косточки, мышки из натурального меха и многое другое.',
        price: 390,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/33/6d/96/23746_400x400.jpg',
        rating: 0,
        categoryType_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'GiGwi барсук, игрушка с двумя пищалками',
        description:
          'Игрушки мягкие и твердые, шуршащие и звенящие, маленькие и побольше. Также в ассортименте производителя Papillon представлены канаты для перетягивания, латексные игрушки для прорезывания зубов, плюшевые косточки, мышки из натурального меха и многое другое.',
        price: 530,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/de/6d/49/498190_400x400.jpg',
        rating: 0,
        categoryType_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Корм NOW FRESH беззерновой "Контроль веса" для собак крупных пород с индейкой, уткой и овощами',
        description:
          'Некоторые кошки определенно мясоеды, что говорит об их хищной природе. Этот беззерновой рецепт богат белками, обеспечивает полноценное и сбалансированное питание, чтобы помочь вашей кошке оставаться здоровой и сохранять отличную физическую форму.',
        price: 3800,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/45/f2/10/539989_400x400.jpg',
        rating: 0,
        categoryType_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Корм GO! для щенков и собак, со свежей уткой и овсянкой',
        description:
          'Рецепты GO! NATURAL SENSITIVITY & SHINE прекрасно подходят для всех типов домашних животных, но изначально разрабатывались для собак и кошек с чувствительным пищеварением. В рецептах тщательно отобраны источники белков, углеводов и необходимые жирные омега-кислоты.',
        price: 5100,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/59/5c/f9/502983_400x400.jpg',
        rating: 0,
        categoryType_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Корм GO! для щенков и собак, со свежей курицей, фруктами и овощами',
        description:
          'Высококачественное мясо кур, выращенных на свободном выгуле, обеспечит вашу собаку незаменимыми аминокислотами для укрепления мышц, а жирные омега-кислоты помогут сохранить здоровую кожу и блестящую шерсть.',
        price: 5170,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/7a/d0/ab/511391_400x400.jpg',
        rating: 0,
        categoryType_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Корм Summit для щенков три вида мяса с ягненком, цыпленком и лососем',
        description:
          'Summit содержит только качественные ингредиенты от давно зарекомендовавших себя фермерских хозяйств компании Petcurean (производители кормов GO! Natural и NOW! Fresh).',
        price: 5270,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/b3/0a/df/220796_400x400.jpg',
        rating: 0,
        categoryType_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Корм Summit для собак три вида мяса c цыпленком, лососем и ягненком',
        description:
          'Сбалансированный корм класса холистик для взрослых собак. Summit содержит только качественные ингредиенты от давно зарекомендовавших себя фермерских хозяйств компании Petcurean (производители кормов GO! Natural и NOW! Fresh).',
        price: 5280,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/35/4f/e5/220797_400x400.jpg',
        rating: 0,
        categoryType_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Корм Italian Way безглютеновый, для собак крупных пород, с курицей и рисом',
        description:
          'Корм Italian Way с курицей и рисом разработан с учетом всех потребностей собак крупных пород.',
        price: 3850,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/44/54/e7/497057_400x400.jpg',
        rating: 0,
        categoryType_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title:
          'Triol бутылка "Жучковское", виниловая игрушка с пищалкой для собак',
        description:
          'Порадуйте себя и своего питомца оригинальной виниловой игрушкой. Бутылка "Жучковского" утолит жажду вашего питомца грызть, а также сбережёт обувь и мебель.',
        price: 300,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/8a/b1/8b/497890_400x400.jpg',
        rating: 0,
        categoryType_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Trixie игрушка "Бургер", плюш, 13 см',
        description: 'Игрушка для собак "Бургер", со звуком, размер: 13 см.',
        price: 590,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/7c/24/d1/558336_400x400.jpg',
        rating: 0,
        categoryType_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Triol игрушка "Спящий барашек" для собак, мягкая шуршащая',
        description:
          'Забавная игрушка с шуршалкой "Спящий барашек" обязательно понравится вашему питомцу. Такую игрушку удобно носить в зубах и вытаскивать из укромных уголков, а шуршащий наполнитель заинтересует собаку любого возраста.',
        price: 330,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/4e/5b/17/561494_400x400.jpg',
        rating: 0,
        categoryType_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Игрушка для животных «Пицца Розетта»',
        description:
          'Яркие и сочные принты привлекут внимание питомца и займут его на продолжительное время. Внутри игрушки находится натуральная кошачья мята для еще большего развлечения и удовольствия!',
        price: 200,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/bf/76/a4/553876_400x400.jpg',
        rating: 0,
        categoryType_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Yami-Yami игрушка для собак "Веселая Морковка"',
        description: 'Отличная игрушка с пищалкой для веселых игр с питомцем.',
        price: 150,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/9f/3e/43/510566_400x400.jpg',
        rating: 0,
        categoryType_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Корм GO! для щенков и собак, со свежим лососем и овсянкой',
        description:
          'Некоторые кошки определенно мясоеды, что говорит об их хищной природе. Этот беззерновой рецепт богат белками, обеспечивает полноценное и сбалансированное питание, чтобы помочь вашей кошке оставаться здоровой и сохранять отличную физическую форму.',
        price: 4600,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/5e/cc/36/511383_400x400.jpg',
        rating: 0,
        categoryType_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'MPets игрушка Ёжик длинный серый мягкая',
        description:
          'Игрушка мягкая MPets Ежик длинный для собак. Подходит для игры дома, а также для активных игр на улице.',
        price: 500,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/41/5f/bb/559195_400x400.jpg',
        rating: 0,
        categoryType_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 1,
      },
      {
        title: 'Tappi амуниция шлейка "Блайнд", с рисунком "Авокадо"',
        description:
          'Стильная шлейка с яркими узорами из качественного нейлона, непременно выделит вашу собаку на прогулке.',
        price: 1000,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/ec/2d/91/542755_400x400.jpg',
        rating: 0,
        categoryType_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Tappi амуниция ошейник "Крэйл", зеленый',
        description:
          'Надежная пряжка-фастекс с замком и качественная фурнитура - гарантируют долгую службу изделия, даже при больших нагрузках.',
        price: 700,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/80/fc/20/541700_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Tappi амуниция поводок "Блайнд", 1,2 м, с рисунком "Авокадо',
        description:
          'Надежная пряжка-фастекс с замком и качественная фурнитура - гарантируют долгую службу изделия, даже при больших нагрузках.',
        price: 890,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/3a/ce/19/542738_400x400.jpg',
        rating: 0,
        categoryType_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Tappi амуниция поводок "Палмер", 1.2 м, с рисунком "Цветы"',
        description:
          'Надежная пряжка-фастекс с замком и качественная фурнитура - гарантируют долгую службу изделия, даже при больших нагрузках.',
        price: 890,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/33/98/a5/542742_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Rogz ошейник серии "Alpinist", красный',
        description:
          'Ошейники из серии  "Alpinist" невероятно мягкие, но при этом долговечные.',
        price: 470,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/09/5a/5a/557229_400x400.jpg',
        rating: 0,
        categoryType_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Rogz поводок 2в1 с системой "антирывок", размер XL, красный',
        description:
          'Поводок 2в1 с системой "антирывок" создан специально для собак, беспорядочно и сильно дергающих поводок. ',
        price: 1600,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/d8/0e/a6/452048_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Rogz поводок 2в1 с системой "антирывок", размер M',
        description:
          'Поводок 2в1 с системой "антирывок" создан специально для собак, беспорядочно и сильно дергающих поводок. ',
        price: 1450,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/7e/11/2f/452036_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Yami-Yami ошейник синтетический светоотражающий',
        description: 'Отличный ошейник для Вашего питомца.',
        price: 150,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/76/92/43/532403_400x400.jpg',
        rating: 0,
        categoryType_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Yami-Yami ошейник со светоотражающим кантом',
        description: 'Отличный ошейник для Вашего питомца.',
        price: 350,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/d2/04/e5/126846_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Yami-Yami светоотражающая шлейка',
        description:
          'Шлейка из синтетического материала со светоотражающей полосой.',
        price: 700,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/52/3b/a0/497054_400x400.jpg',
        rating: 0,
        categoryType_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Tappi амуниция светодиодный ошейник "Кейн", красный',
        description:
          'Раскрасьте серые будни яркими и стильными светодиодными ошейниками Tappi!',
        price: 1100,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/f6/ba/4f/550644_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Tappi амуниция светодиодный ошейник "Райз", чёрный',
        description:
          'Вы можете самостоятельно сгенерировать надпись на ошейнике, указав имя питомца, номер телефона или иную необходимую информацию',
        price: 2300,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/09/5d/cb/550734_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Ferribiella аксессуары силиконовый поводок "Фанни", розовый',
        description:
          'Идеально сочетается с ошейниками Ferribiella, при этом цвета можно комбинировать.',
        price: 600,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/f6/f7/35/439830_400x400.jpg',
        rating: 0,
        categoryType_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Hunter hunter LED Поводок Manoa Glow, желтый',
        description: 'Поводок LED светодиодный. Зарядка через USB.',
        price: 2300,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/b0/e2/b0/497499_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Petsee GPS-ошейник, чёрный',
        description: 'Поводок LED светодиодный. Зарядка через USB.',
        price: 3500,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/84/92/3c/520729_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title:
          'Ferribiella аксессуары cветящийся тонкий силиконовый ошейник, розовый',
        description:
          'Плоские ошейники ярких неоновых расцветок помогут вам разглядеть заигравшегося в траве питомца.',
        price: 910,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/af/ff/9e/444028_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Hunter hunter Smart поводок для собак Ecco, нейлон бирюзовый',
        description:
          'Выполнен из нейлона, имеет удобную петлю для руки, а также надежный карабин для сцепления с ошейником.',
        price: 310,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/47/df/8a/497831_400x400.jpg',
        rating: 0,
        categoryType_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Yami-Yami брезентовый поводок с карабином',
        description:
          'Качественный и недорогой поводок от Yami-Yami - незаменимый аксессуар для прогулок с питомцем.',
        price: 410,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/47/81/2f/505783_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title:
          'Yami-Yami двухслойный кожаный поводок "Брайт" с карабином, красный',
        description: 'Двухслойный кожаный поводок "Брайт" с карабином.',
        price: 490,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/ae/3e/f4/496746_400x400.jpg',
        rating: 0,
        categoryType_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title: 'Ferribiella аксессуары кожаный поводок "Альберто" голубой',
        description:
          'Кожаные поводки известны своей прочностью и долговечностью.',
        price: 1490,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/9d/d7/95/417529_400x400.jpg',
        rating: 0,
        categoryType_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },

      {
        title: 'Tappi одежда комбинезон "Фронроу" без подкладки, серый',
        description:
          'Универсальный комбинезон из мембранной ткани с трикотажными манжетами и отстегивающимся капюшоном',
        price: 1640,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/73/ab/3f/536968_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },

      {
        title: 'Lelap жилетка "Грандэ" для собак, черная',
        description:
          'Стильные утепленные жилетки с эксклюзивными дизайнерскими принтами.',
        price: 1955,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/3e/02/95/552458_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },

      {
        title: 'Tappi одежда бандана "Баден", розовая',
        description:
          'Удиви всех своим фирменным стилем вместе с аксессуарами Tappi! ',
        price: 250,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/1d/9a/69/536894_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },

      {
        title: 'Yami-Yami одежда рубашка для собак, бежевая',
        description:
          'Красочная и комфортная рубашка для питомца на каждый день!',
        price: 670,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/1c/72/a1/547788_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },

      {
        title: 'OSSO футболка для собак «Сафари»',
        description:
          'Футболка для любой маленькой собачки  всегда актуальна в гардеробе жарким и пыльным летом',
        price: 240,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/d7/e1/2a/554583_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },

      {
        title: 'Yami-Yami одежда куртка для собак, желтая',
        description:
          'Cтильные и яркие курточки для настоящих модников, идеальное решение для прогулок.',
        price: 927,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/ab/28/18/547759_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },

      {
        title: 'Ferribiella одежда жилет из экокожи "Харли" (бежевый)',
        description:
          'Настоящий итальянский шик и удобство - жилет роскошных цветов из-экокожи.',
        price: 927,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/6f/99/2b/353385_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },

      {
        title: 'Pinkaholic козырек с совами, голубой',
        description:
          'Стильный козырек для вашего питомца придаст ему оригинальности',
        price: 623,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/bc/77/2d/343725_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },

      {
        title:
          'Yami-Yami одежда комбинезон для йорк-терьера, с рисунком "камуфляж',
        description:
          'Дождевик с водотталкивающей пропиткой позволит вашему питомцу оставаться сухим и чистым во время прогулок в дождливую погоду.',
        price: 840,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/7e/73/de/516043_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
      {
        title:
          'Yami-Yami одежда комбинезон для собак, на флисовой подкладке, коричнево-розовый',
        description:
          'Комбинезон Yami-Yami на флисовой подкладке надежно защитит Вашего питомца от холода и сильного ветра. ',
        price: 1336,
        img: 'https://6kcmxu3d7l.a.trbcdn.net/upload/files-new/be/e6/bb/559122_400x400.jpg',
        rating: 0,
        categoryType_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        amount: 20,
      },
    ]);
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('Items', null, {});
  },
};
